### ISSUE TITLE
v2.1.6 can not `create_app`

### ISSUE THREAD

**Issue by ctarn** [JuliaLang/PackageCompiler.jl#812]
I upgraded PackageCompiler to v2.1.6 and found out that my apps can not be successfully built. I re-tested it on `examples/MyApp` and it failed again.

versioninfo
```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
```

prepare
```
julia> using Pkg

julia> Pkg.status()
Project MyApp v0.1.0
Status `~/tmp/PackageCompiler.jl/examples/MyApp/Project.toml`
  [a8cc5b0e] Crayons v4.1.1
  [7876af07] Example v0.5.3
  [dca1746e] HelloWorldC_jll v1.2.1+1
  [dad2f222] LLVMExtra_jll v0.0.21+0
  [f8abcde7] micromamba_jll v1.4.3+0
  [56f22d72] Artifacts
  [8ba89e20] Distributed
  [9a3f8284] Random

julia> Pkg.instantiate()
    Updating registry at `~/.julia/registries/General.toml`
   Installed micromamba_jll ── v1.4.3+0
   Installed LLVMExtra_jll ─── v0.0.21+0
   Installed Example ───────── v0.5.3
   Installed HelloWorldC_jll ─ v1.2.1+1
  Downloaded artifact: LLVMExtra
  Downloaded artifact: HelloWorldC
  Downloaded artifact: fooifier
    Updating `~/tmp/PackageCompiler.jl/examples/MyApp/Project.toml`
  [a8cc5b0e] + Crayons v4.1.1
  [7876af07] + Example v0.5.3
  [dca1746e] + HelloWorldC_jll v1.2.1+1
  [dad2f222] + LLVMExtra_jll v0.0.21+0
  [f8abcde7] + micromamba_jll v1.4.3+0
    Updating `~/tmp/PackageCompiler.jl/examples/MyApp/Manifest.toml`
  [a8cc5b0e] + Crayons v4.1.1
  [7876af07] + Example v0.5.3
  [692b3bcd] + JLLWrappers v1.4.1
  [21216c6a] + Preferences v1.4.0
  [dca1746e] + HelloWorldC_jll v1.2.1+1
  [dad2f222] + LLVMExtra_jll v0.0.21+0
  [f8abcde7] + micromamba_jll v1.4.3+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.3
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.9.0
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll v7.84.0+0
  [29816b5a] + LibSSH2_jll v1.10.2+0
  [c8ffd9c3] + MbedTLS_jll v2.28.2+0
  [14a3606d] + MozillaCACerts_jll v2022.10.11
  [83775a58] + Zlib_jll v1.2.13+0
  [8e850ede] + nghttp2_jll v1.48.0+0
  [3f19e933] + p7zip_jll v17.4.0+0
Precompiling project...
  5 dependencies successfully precompiled in 12 seconds. 6 already precompiled.
  1 dependency had warnings during precompilation:
┌ MyApp [f943f3d7-887a-4ed5-b0c0-a1d6899aa8f5]
│   Downloading artifact: micromamba
└  
```

error log
```
julia> import PackageCompiler

julia> PackageCompiler.create_app(".", "build.tmp", force=true)
PackageCompiler: bundled artifacts:
  ├── HelloWorldC_jll - 23.669 KiB
  ├── LLVMExtra_jll - 95.938 KiB
  └── MyApp
      └── fooifier - 14.124 KiB
  Total artifact file size: 133.730 KiB
✔ [02m:32s] PackageCompiler: compiling base system image (incremental=false)
Precompiling project...
  11 dependencies successfully precompiled in 46 seconds
⢰ [00m:12s] PackageCompiler: compiling nonincremental system imageUndefVarError: `MyApp` not defined
Stacktrace:
 [1] top-level scope
   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_E7IPmXOVi5:115
⣄ [00m:13s] PackageCompiler: compiling nonincremental system imageModule, e::Any)
   @ Core ./boot.jl:370
 [3] top-level scope
   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_E7IPmXOVi5:114
 [4] eval(m::Module, e::Any)
   @ Core ./boot.jl:370
 [5] top-level scope
   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_E7IPmXOVi5:49
in expression starting at /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_E7IPmXOVi5:49
✖ [00m:13s] PackageCompiler: compiling nonincremental system image
ERROR: failed process: Process(`/Users/i/.julia/juliaup/julia-1.9.0+0.x64.apple.darwin14/bin/julia --color=yes --startup-file=no --pkgimages=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' --sysimage=/var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_mSq9e6/sys.ji --project=/Users/i/tmp/PackageCompiler.jl/examples/MyApp --output-o=/var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_IhsvsjeV6h.o /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_E7IPmXOVi5`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:480
  [3] run
    @ ./process.jl:477 [inlined]
  [4] #20
    @ ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:157 [inlined]
  [5] spin(f::PackageCompiler.var"#20#22"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
    @ PackageCompiler.TerminalSpinners ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:164
  [6] macro expansion
    @ ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:157 [inlined]
  [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:128
  [8] create_sysimg_object_file
    @ ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:290 [inlined]
  [9] create_sysimage(packages::Vector{String}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:586
 [10] create_sysimage
    @ ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:484 [inlined]
 [11] create_app(package_dir::String, app_dir::String; executables::Nothing, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, force::Bool, c_driver_program::String, cpu_target::String, include_lazy_artifacts::Bool, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, script::Nothing)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:809
 [12] top-level scope
    @ REPL[4]:1
```

**Comment by ctarn** [comment]
I tested both the example app and my own app with v.2.1.5, and both can be successfully built.
I also created a mini app as below. It can also be built with v.2.1.5 but not v.2.1.6.

prepare
```
i@ctarn ~/t/P/e/MiniApp (master)> ls . src
.:
Project.toml  src/

src:
MiniApp.jl
i@ctarn ~/t/P/e/MiniApp (master)> cat Project.toml 
name = "MiniApp"
uuid = "f943f3d7-887a-4ed5-b0c0-a1d6899aa8f6"
version = "0.1.0"
i@ctarn ~/t/P/e/MiniApp (master)> cat src/MiniApp.jl
module MiniApp

function julia_main()::Cint
    println("this is MiniApp")
    return 0
end

end
```

build with v2.1.6
```
i@ctarn ~/t/P/e/MiniApp (master)> julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0 (2023-05-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(MiniApp) pkg> add PackageCompiler@2.1.6
   Resolving package versions...
    Updating `~/tmp/PackageCompiler.jl/examples/MiniApp/Project.toml`
  [9b87118b] + PackageCompiler v2.1.6
    Updating `~/tmp/PackageCompiler.jl/examples/MiniApp/Manifest.toml`
  [9b87118b] + PackageCompiler v2.1.6
  [05181044] + RelocatableFolders v1.0.0
  [6c6a2e73] + Scratch v1.2.0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.3
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.9.0
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll v7.84.0+0
  [29816b5a] + LibSSH2_jll v1.10.2+0
  [c8ffd9c3] + MbedTLS_jll v2.28.2+0
  [14a3606d] + MozillaCACerts_jll v2022.10.11
  [83775a58] + Zlib_jll v1.2.13+0
  [8e850ede] + nghttp2_jll v1.48.0+0
  [3f19e933] + p7zip_jll v17.4.0+0

julia> import PackageCompiler

julia> PackageCompiler.create_app(".", "build.tmp", force=true)
✔ [02m:38s] PackageCompiler: compiling base system image (incremental=false)
Precompiling project...
  7 dependencies successfully precompiled in 43 seconds
⣄ [00m:13s] PackageCompiler: compiling nonincremental system imageUndefVarError: `MiniApp` not defined
Stacktrace:
 [1] top-level scope
⡆ [00m:13s] PackageCompiler: compiling nonincremental system image   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_zu5Inu3uhe:110
⠋ [00m:13s] PackageCompiler: compiling nonincremental system imageModule, e::Any)
   @ Core ./boot.jl:370
 [3] top-level scope
   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_zu5Inu3uhe:109
 [4] eval(m::Module, e::Any)
   @ Core ./boot.jl:370
 [5] top-level scope
   @ /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_zu5Inu3uhe:44
in expression starting at /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_zu5Inu3uhe:44
✖ [00m:13s] PackageCompiler: compiling nonincremental system image
ERROR: failed process: Process(`/Users/i/.julia/juliaup/julia-1.9.0+0.x64.apple.darwin14/bin/julia --color=yes --startup-file=no --pkgimages=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' --sysimage=/var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_8f3pFX/sys.ji --project=/Users/i/tmp/PackageCompiler.jl/examples/MiniApp --output-o=/var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_dYb0jWZGHS.o /var/folders/r3/y1sclb514fxbrwhgpk1vk2x00000gn/T/jl_zu5Inu3uhe`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:480
  [3] run
    @ ./process.jl:477 [inlined]
  [4] #20
    @ ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:157 [inlined]
  [5] spin(f::PackageCompiler.var"#20#22"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
    @ PackageCompiler.TerminalSpinners ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:164
  [6] macro expansion
    @ ~/.julia/packages/PackageCompiler/3niuD/ext/TerminalSpinners.jl:157 [inlined]
  [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:128
  [8] create_sysimg_object_file
    @ ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:290 [inlined]
  [9] create_sysimage(packages::Vector{String}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:586
 [10] create_sysimage
    @ ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:484 [inlined]
 [11] create_app(package_dir::String, app_dir::String; executables::Nothing, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, force::Bool, c_driver_program::String, cpu_target::String, include_lazy_artifacts::Bool, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, script::Nothing)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/3niuD/src/PackageCompiler.jl:809
 [12] top-level scope
    @ REPL[2]:1
```

build with v2.1.5
```
i@ctarn ~/t/P/e/MiniApp (master)> julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0 (2023-05-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(MiniApp) pkg> add PackageCompiler@2.1.5
   Resolving package versions...
    Updating `~/tmp/PackageCompiler.jl/examples/MiniApp/Project.toml`
⌃ [9b87118b] ↓ PackageCompiler v2.1.6 ⇒ v2.1.5
    Updating `~/tmp/PackageCompiler.jl/examples/MiniApp/Manifest.toml`
⌃ [9b87118b] ↓ PackageCompiler v2.1.6 ⇒ v2.1.5
        Info Packages marked with ⌃ have new versions available and may be upgradable.

julia> import PackageCompiler

julia> PackageCompiler.create_app(".", "build.tmp", force=true)
✔ [02m:36s] PackageCompiler: compiling base system image (incremental=false)
Precompiling project...
  7 dependencies successfully precompiled in 43 seconds
✔ [01m:17s] PackageCompiler: compiling nonincremental system image

julia> 
i@ctarn ~/t/P/e/MiniApp (master)> ./build.tmp/bin/MiniApp 
this is MiniApp
```

**Comment by KristofferC** [comment]
I understand why this happens. It currently will only happen if you have no precompile statements at all coming from the app so it is unlikely to happen in real use cases. But should be fixed nonetheless.

**Comment by ctarn** [comment]
Thanks for your response! Actually, I never use a `precompile` file in my project. Why is it necessary? Could you please provide me with some references?

**Comment by 13299118606** [comment]
I also encountered this problem, and I said that I couldn’t find a solution to the problem, and I thought it was because of the problem of julia 1.9.0. I rolled back to 1.7.0, and 1.8.3 did not solve the problem. It turned out to be the package Version problem, thank you very much for your solution, I rolled back PackageCompiler to 2.1.5 to solve this problem!

**Comment by StefanPofahl** [comment]
Unfortunatly my example is rather complex, nothing to share here ...
But I can confirm, with the new version, I encounter issues, with both Julia versions:
v1.8.5 as well as v1.9.0
If relevant, I can share more information or can run specific tests.

**Comment by ctarn** [comment]
Thanks for your efforts. It does work perfectly now.

**Comment by StefanPofahl** [comment]
Thanks a lot for the new version!!!
Unfortunately, my issue is not yet resolved by  [#813](https://github.com/JuliaLang/PackageCompiler.jl/pull/813).
I hope the following messages might be helpful:
```
┌ Debug: running `'C:\bin\juliaRC\bin\julia.exe' --color=yes --startup-file=no --pkgimages=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' '--sysimage=C:\Users\STEFAN~1\AppData\Local\Temp\jl_z2jXSO\sys.ji' '--project=C:\data\git_repos\hycenta_stefan_pofahl\julia_apps\tmp_RC_InteractiveNyquist' '--output-o=C:\Users\STEFAN~1\AppData\Local\Temp\jl_SDEn0xexYP.o' 'C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5'`
└ @ PackageCompiler C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:428
⠙ [00m:36s] PackageCompiler: compiling nonincremental system imageUndefVarError: `InteractiveNyquist` not defined
Stacktrace:
 [1] top-level scope
   @ C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5:340
⣠ [00m:36s] PackageCompiler: compiling nonincremental system imageModule, e::Any)
   @ Core .\boot.jl:370
 [3] top-level scope
   @ C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5:339
 [4] eval(m::Module, e::Any)
   @ Core .\boot.jl:370
 [5] top-level scope
   @ C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5:274
in expression starting at C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5:274
✖ [00m:36s] PackageCompiler: compiling nonincremental system image
ERROR: LoadError: failed process: Process(`'C:\bin\juliaRC\bin\julia.exe' --color=yes --startup-file=no --pkgimages=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' '--sysimage=C:\Users\STEFAN~1\AppData\Local\Temp\jl_z2jXSO\sys.ji' '--project=C:\data\git_repos\hycenta_stefan_pofahl\julia_apps\tmp_RC_InteractiveNyquist' '--output-o=C:\Users\STEFAN~1\AppData\Local\Temp\jl_SDEn0xexYP.o' 'C:\Users\STEFAN~1\AppData\Local\Temp\jl_OPabUjgnU5'`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ .\process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base .\process.jl:480
  [3] run
    @ .\process.jl:477 [inlined]
  [4] #20
    @ C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\ext\TerminalSpinners.jl:157 [inlined]
  [5] spin(f::PackageCompiler.var"#20#22"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
    @ PackageCompiler.TerminalSpinners C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\ext\TerminalSpinners.jl:164
  [6] macro expansion
    @ C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\ext\TerminalSpinners.jl:157 [inlined]
  [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
    @ PackageCompiler C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:128
  [8] create_sysimg_object_file
    @ C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:290 [inlined]
  [9] create_sysimage(packages::Vector{String}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
    @ PackageCompiler C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:586
 [10] create_sysimage
    @ C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:484 [inlined]
 [11] create_app(package_dir::String, app_dir::String; executables::Vector{Pair{String, String}}, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, force::Bool, c_driver_program::String, cpu_target::String, include_lazy_artifacts::Bool, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, script::Nothing)
    @ PackageCompiler C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:809
 [12] create_app
    @ C:\Users\stefanpofahl\.julia\packages\PackageCompiler\3niuD\src\PackageCompiler.jl:759 [inlined]
 [13] compile_it()
    @ Main C:\data\git_repos\hycenta_stefan_pofahl\julia_apps\tmp_start_PC_RC_c#4.jl:23
 [14] top-level scope
    @ .\timing.jl:273
in expression starting at C:\data\git_repos\hycenta_stefan_pofahl\julia_apps\tmp_start_PC_RC_c#4.jl:26

C:\data\git_repos\hycenta_stefan_pofahl\julia_apps>

```

**Comment by KristofferC** [comment]
Do you have code that reproduces that problem that I can run?

**Comment by StefanPofahl** [comment]
Under Ubuntu 22.04 I had no problems to compile "case_nr = 5":
       s_app       = "InteractiveNyquist"
:-)
MS-Window-Test is still running ...

**Comment by StefanPofahl** [comment]
Recently I tested also the two simple examples of my repo mentioned above:
case_nr  = 1 (MyAppHelloTulip)
case_nr  = 2 (MyTOML)
Both are crashing as well on my machine under Windows:
```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_SSL_CA_ROOTS_PATH =
```

**Comment by StefanPofahl** [comment]
@KristofferC:
Hi Kristoffer!
The two examples mentioned above are really some kind of minimal examples. May I ask, if you found the time to investigate?

**Comment by StefanPofahl** [comment]
@KristofferC 
Hi Kristoffer!

The issue under MS-WIN seems to be fixed with the new Julia version v9.1! 

Looking forward to the next PackageCompiler.jl-Version :-)

Regards,

Stefan
